#!/usr/bin/env bash
#process and PID

file=/var/run/myscript.pid
function remove {
	sudo rm $file
	exit
}

function killingDem {
	echo 'I hate the kill command'
	sudo rm $file
	exit
}

trap killingDem SIGTERM
trap remove SIGQUIT
trap "echo 'Y U no love me?!'" SIGINT
sudo bash -c "echo $$ > $file"
while ((1))
do
	echo "To infinity and beyond"
	sleep 2
done
